### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by NaraDum** [DumNara/ShareProject#2]
This is issues..........
![screenshot 1](https://cloud.githubusercontent.com/assets/14134111/9702050/af048fce-5476-11e5-9d04-6f5ff62b426c.png)

**Comment by yaborin** [comment]
Hi i been finish

Please check.

![0 2](https://cloud.githubusercontent.com/assets/11530574/9702055/049f3dbc-5477-11e5-8b03-c001111e05a8.jpg)
